doc: AidLux部署教程整合
lss233/chatgpt-for-bot-docs pull request #3
Opened 2023-05-24 18:41 UTC by B17w153

rt

2023-05-24 18:47 UTC, lss233 requested changes

2023-05-24 18:47 UTC, lss233 commented on bu-shu-jiao-cheng/kuai-su-bu-shu-jiao-cheng/README.md
> +对于 Linux 安卓模拟器（aidlux），请阅读:
我觉得可以强调下是纯手机部署的方法？

2023-05-24 18:47 UTC, lss233 commented on bu-shu-jiao-cheng/kuai-su-bu-shu-jiao-cheng/aidlux-bu-shu-jiao-cheng.md
> +# 安卓Linux模拟器AidLux部署教程
为了匹配之前的文章编写风格，请在中文和英文之间加上空格。

2023-05-24 18:47 UTC, lss233 commented on bu-shu-jiao-cheng/kuai-su-bu-shu-jiao-cheng/aidlux-bu-shu-jiao-cheng.md
> +![image](https://github.com/B17w153/chatgpt-for-bot-docs/assets/134407644/0df8171b-171c-41ac-b6fe-847139fc54d6)
可以把原 README.md 中的文本介绍直接移至此处。 这样原项目 README.md 只需要引导用户到这里看教程就好了。  

这样如果以后部署步骤有修改，我们只需要更新文档即可，不需要再修改原项目 README.md

2023-05-24 18:50 UTC, B17w153 commented on bu-shu-jiao-cheng/kuai-su-bu-shu-jiao-cheng/README.md
> +对于 Linux 安卓模拟器（aidlux），请阅读:
可以

2023-05-24 18:50 UTC, B17w153 commented on bu-shu-jiao-cheng/kuai-su-bu-shu-jiao-cheng/aidlux-bu-shu-jiao-cheng.md
> +# 安卓Linux模拟器AidLux部署教程
在改

2023-05-24 18:50 UTC, B17w153 commented on bu-shu-jiao-cheng/kuai-su-bu-shu-jiao-cheng/aidlux-bu-shu-jiao-cheng.md
> +![image](https://github.com/B17w153/chatgpt-for-bot-docs/assets/134407644/0df8171b-171c-41ac-b6fe-847139fc54d6)
彳亍

2023-05-24 19:17 UTC, B17w153 reviewed
1

2023-05-24 19:38 UTC, B17w153 commented
修改完了，核查一下吧

2023-05-25 16:53 UTC, lss233 commented
感谢！

2023-05-25 16:53 UTC, lss233 approved these changes

2023-05-25 16:54 UTC, merged